#!/bin/bash

molecules=$(ls -d */ | sed 's:/*$::')
# molecules="1TD4"  
functionals=("M062X")
states=("s0" "s1" "t1")
  s0=1; s1=2; t1=3
  o3lyp=1; pbe0=2; cam=3; m062x=4; wb97x=5
  tddft=1;Dscf=2
  optfreq=1; fluo=4; isc=5; risc=6
for molecule in $molecules; do
    # echo "molecule: $molecule"
    if [[ ! "$molecule" =~ ^[0-9] ]]; then
      continue
    fi
    cd $molecule
    echo "Molecule: $molecule"

    for functional in "${functionals[@]}"; do
        GS="$molecule"_"$functional"_svp_s0_scf_optfreq
        ES=${molecule}_${functional}_svp_s1_Dscf_optfreq
        ES_tddft=${molecule}_${functional}_svp_s1_tddft_optfreq
        TS="$molecule"_"$functional"_svp_t1_Dscf_optfreq
        TS_scf="$molecule"_"$functional"_svp_t1_scf_optfreq
        FLUO="$molecule"_"$functional"_svp_s1_esd_fluo
        ISC_1="$molecule"_"$functional"_svp_t1_esd_isc_T1
        ISC_2="$molecule"_"$functional"_svp_t1_esd_isc_T2
        RISC_1="$molecule"_"$functional"_svp_t1_esd_risc_T1
        RISC_2="$molecule"_"$functional"_svp_t1_esd_risc_T2
        

        # Check Ground state file 
        if [ ! -f "$GS.out" ]; then
            echo "#### File not found: $GS.out"
            echo "Submitting file"
            if [ -f $molecule.xyz ]; then
                echo "Running:: ORCA-Input $molecule $molecyule.xyz $s0 $optfreq $m062x"
                ORCA-Input $molecule $molecyule.xyz $s0 $optfreq $m062x > /dev/null
            fi

            if [ -f ${molecule}_S0.xyz ]; then
                echo "Running:: ORCA-Input $molecule ${molecule}_S0.xyz $s0 $optfreq $m062x"
                ORCA-Input $molecule ${molecule}_S0.xyz $s0 $optfreq $m062x > /dev/null
            fi
        else 
            finished=$(grep -c "****ORCA TERMINATED NORMALLY****" $GS.out)
            if [ $finish -eq 1 ]; then
                echo "#### $GS.out ORCA terminated normally."
            else
                echo "#### $GS.out ORCA did not terminate normally."
                if [ -f $molecule.xyz ]; then
                    echo "Running:: ORCA-Input $molecule $molecyule.xyz $s0 $optfreq $m062x"
                    ORCA-Input $molecule $molecyule.xyz $s0 $optfreq $m062x > /dev/null
                fi

                if [ -f ${molecule}_S0.xyz ]; then
                    echo "Running:: ORCA-Input $molecule ${molecule}_S0.xyz $s0 $optfreq $m062x"
                    ORCA-Input $molecule ${molecule}_S0.xyz $s0 $optfreq $m062x > /dev/null
                fi
            fi
        fi
        
        # Check Excited state file
        if [ ! -f $ES.out ]; then
            echo "#### File not found: $ES.out"
            echo "Submitting file"

            echo "Running:: ORCA-Input $molecule $GS.xyz $s1 $Dscf $m062x"
            ORCA-Input $molecule $molecyule.xyz $s1 $Dscf $m062x > /dev/null
        else
            finished=$(grep -c "****ORCA TERMINATED NORMALLY****" $ES.out)
            if [ $finish -eq 1 ]; then
                echo "#### $ES.out ORCA terminated normally."
            else
                echo "#### $ES.out ORCA did not terminate normally."
                echo "Running:: ORCA-Input $molecule $GS.xyz $s1 $Dscf $m062x"
                ORCA-Input $molecule $molecyule.xyz $s1 $Dscf $m062x > /dev/null
            fi
        fi

        if [ ! -f $TS.out ]; then 
            echo "#### File not found: $TS.out"
            echo "Submitting file"

            echo "Running:: ORCA-Input $molecule $GS.xyz $t1 $Dscf $m062x"
            ORCA-Input $molecule $molecyule.xyz $t1 $Dscf $m062x > /dev/null
        else
            finished=$(grep -c "****ORCA TERMINATED NORMALLY****" $TS.out)
            if [ $finish -eq 1 ]; then
                echo "#### $TS.out ORCA terminated normally."
            else
                echo "#### $TS.out ORCA did not terminate normally."
                echo "Running:: ORCA-Input $molecule $GS.xyz $t1 $Dscf $m062x"
                ORCA-Input $molecule $molecyule.xyz $t1 $Dscf $m062x > /dev/null
            fi
        fi
        
        if [ ! -f $TS_scf.out ]; then
            echo "#### File not found: $TS_scf.out"
            echo "Submitting file"

            echo "Running:: ORCA-Input $molecule $GS.xyz $t1 $tddft $m062x"
            ORCA-Input $molecule $molecyule.xyz $t1 $tddft $m062x > /dev/null
        else
            finished=$(grep -c "****ORCA TERMINATED NORMALLY****" $TS_scf.out)
            if [ $finish -eq 1 ]; then
                echo "#### $TS_scf.out ORCA terminated normally."
            else
                echo "#### $TS_scf.out ORCA did not terminate normally."
                echo "Running:: ORCA-Input $molecule $GS.xyz $t1 $tddft $m062x"
                ORCA-Input $molecule $molecyule.xyz $t1 $tddft $m062x > /dev/null
            fi
        fi        

        if [ ! -f $FLUO.out ]; then
            echo "#### File not found: $FLUO.out"
            echo "Submitting file"

            echo "Running:: ORCA-Input $molecule $GS.xyz $s0 $fluo $m062x"
            ORCA-Input $molecule  $molecule $GS.xyz $s0 $fluo $m062x > /dev/null
        else
            finished=$(grep -c "****ORCA TERMINATED NORMALLY****" $FLUO.out)
            if [ $finish -eq 1 ]; then
                echo "#### $FLUO.out ORCA terminated normally."
            else
                echo "#### $FLUO.out ORCA did not terminate normally."
                echo "Running:: ORCA-Input  $molecule $GS.xyz $s0 $fluo $m062x"
                ORCA-Input $molecule  $molecule $GS.xyz $s0 $fluo $m062x > /dev/null
            fi
        fi
    done
    cd ..
done
