#!/bin/bash

molecules=$(ls -d */ | sed 's:/*$::')
# molecules="1TD4"  
functionals=("O3LYP" "pbe0" "camB3LYP" "M062X") #"wB97XD4")
states=("s0" "s1" "t1")
 
# csv_file="CM5192_calculation_data.csv"
if [ -z "$1" ]; then
  output="soc_isc.csv"
else
  output=${1}_isc.csv
fi

echo "Molecule_Name,Functional,ISC_Rate,npoints1,npoints2,K_Vector_sum,lamda_sum(cm-1),lamda_max_freq,lamda_maxmode_socme,HR_max_freq,HR_maxmode_socme,rmsf_s1_t1" > $output


for molecule in $molecules; do
    # echo "molecule: $molecule"
    if [[ ! "$molecule" =~ ^[0-9] ]]; then
      continue
    fi
    cd $molecule
    echo "Molecule: $molecule"
    ref="0${molecule:1:2}0"
    # echo "Reference: $ref"

    for functional in "${functionals[@]}"; do
        GS="$molecule"_"$functional"_svp_s0_scf_optfreq
        ES=${molecule}_${functional}_svp_s1_Dscf_optfreq
        TS="$molecule"_"$functional"_svp_t1_Dscf_optfreq
        FLUO="$molecule"_"$functional"_svp_s1_esd_fluo
        ISC_1="$molecule"_"$functional"_svp_t1_esd_isc_T1
        ISC_2="$molecule"_"$functional"_svp_t1_esd_isc_T2
        ISC_3="$molecule"_"$functional"_svp_t1_esd_isc_T3

        files=($GS $ES $TS $FLUO $ISC_1 $ISC_2 $ISC_3 )

        # check imaginary modes
        for s in $GS $ES $TS; do
            if [ ! -f "$s.hess" ]; then
                echo $s
                hess=1
            else
                freq=`grep --text "vibrational_frequencies" -A 8 $s.hess | tail -n 1 | awk '{print $2}'`
                if [[ "$freq" == -* ]]; then
                    echo $s.hess
                    # echo "Frequency 6: $freq"
                    hess=1
                else
                    hess=0
                fi
            fi
        done

        
        


        ISC_rate_1=$(ORCA-Grepk -q "$ISC_1.out")
        ISC_rate_2=$(ORCA-Grepk -q "$ISC_2.out")
        ISC_rate_3=$(ORCA-Grepk -q "$ISC_3.out")


        if [ -z $ISC_rate_3 ] && [ "$ISC_rate_1" != "0.00000000e+00" ]; then
            ISC_rate_3=$ISC_rate_1
            # echo "Replaced RISC rate 3 with RISC rate 1"
        elif [ -z $ISC_rate_1 ] && [ "$ISC_rate_3" != "0.00000000e+00" ]; then
            ISC_rate_1=$ISC_rate_3
        fi
        ISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$ISC_rate_1" "$ISC_rate_2" "$ISC_rate_3" | bc -l 2>/dev/null)


        if [ "$ISC_sum" != "0.00000000e+00" ]; then
            if (( $(echo "$ISC_sum < 0" | bc -l) )); then
                # echo "Negative RISC rate for $molecule with $functional"
                ISC_average="NaN"
            else
                ISC_average=$(printf "%.10g / 3\n" "$ISC_sum" | bc -l 2>/dev/null)
                # echo "RISC average: $ISC_average"
            fi
        else
            ISC_average=0.0000000000
        fi

        ORCA-GrepVC $ISC_1.out 

        if [ ! -f "${ISC_1}.out" ]; then
            # echo "Error: ${ISC_1}.out not found"
            lamda_max_freq=0
            lamda_maxmode_socme="0"
            HR_max_freq=0
            HR_maxmode_socme="0"
            lamda=0
            K_vector=0
            npints=0
            continue
        fi

        lamda=$(grep "The total reorganization energy is:" $ISC_1.out | awk '{print $6}')
        K_vector=$(grep "The sum of K" $ISC_1.out | awk '{print $6}')
        lamda_max_freq=$(sort -k2,2n ${ISC_1}_lamda.data | tail -n 1| awk '{print $3}')
        lamda_max_mode=$(sort -k2,2n ${ISC_1}_lamda.data | tail -n 1| awk '{print $1}')
        lamda_maxmode_socme=$(grep -w "$lamda_max_mode " ${ISC_1}_socme.data | awk '{print $2 $3}')
        # echo "lamda_maxmode_socme: $lamda_maxmode_socme"

        HR_max_freq=$(sort -k2,2n ${ISC_1}_HR.data | tail -n 1| awk '{print $3}')
        HR_max_mode=$(sort -k2,2n ${ISC_1}_HR.data | tail -n 1| awk '{print $1}')
        HR_maxmode_socme=$(grep -w "$HR_max_mode " ${ISC_1}_socme.data | awk '{print $2 $3}')
        # echo "HR_maxmode_socme: $HR_maxmode_socme"
        npoints1=$(grep "Number of points:" $ISC_1.out | awk '{print $4}')
        npoints2=$(grep "Number of points:" $ISC_2.out | awk '{print $4}')
        HR_maxmode_socme1=$(grep -w "$HR_max_mode " ${ISC_1}_socme.data | awk '{print $2 $3}')
        HR_maxmode_socme2=$(grep -w "$HR_max_mode " ${ISC_2}_socme.data | awk '{print $2 $3}')


        XYZ_T1_S1=$(grep "The RMSD is" $ISC_1.out | awk '{print $4}')
      

        ISC_rate_1=$(printf "%.8e" "$ISC_rate_1")
        ISC_rate_2=$(printf "%.8e" "$ISC_rate_2")
        ISC_rate_3=$(printf "%.8e" "$ISC_rate_3")
        ISC_average=$(printf "%.8e" "$ISC_average")
        XYZ_S1_S0=$(printf "%.10f" "$XYZ_S1_S0")
        XYZ_T1_S1=$(printf "%.10f" "$XYZ_T1_S1")
        XYZ_T1_S0=$(printf "%.10f" "$XYZ_T1_S0")
    

        echo "\"${molecule}\",\"${functional}\",\"$ISC_average\",\"$npoints1\",\"$npoints2\",\"$K_vector\",\"$lamda\",\"$lamda_max_freq\",\"$lamda_maxmode_socme\",\"$HR_max_freq\",\"$HR_maxmode_socme\",\"$XYZ_T1_S1\"" >> ../$output

        


    done
    cd ..
done



# echo "Data has been processed and saved to $output"