#!/bin/bash

molecules=$(ls -d */ | sed 's:/*$::')
# molecules=("1OB1" "1OB2" "1OB3" "1OB4")
# functionals=("O3LYP" "pbe0" "camB3LYP" "M062X" ) #"wB97XD4")
functionals=("O3LYP")
states=("s0" "s1" "t1")
# echo "Molecules: ${molecules[@]}"
# csv_file="CM5192_calculation_data.csv"
if [ -z "$1" ]; then
  output="data.csv"
else
  output=${1}_rate.csv
fi

echo "Molecule,Functional,S0,S1_Dscf,S1_td,T1,ST_eV,ST_Add,k_F,ISC1,ISC2,ISC3,k_isc,RISC1,RISC2,RISC3,k_risc,k_ct,emission,ref_molecule" > $output

Initial_State() {
  local list=("$1")
  local file=${list%.*}.out
  # echo $file
  # 1. Check that the job is finished if not finished, return 0
  local finish=0
  local finish=$(grep "****ORCA ESD FINISHED WITHOUT ERROR****" $file | wc -l)
  # if [ $finish -eq 0 ]; then
  #   echo "99"
  #   return 
  # fi
  # grep "ISCISHESS" $file | awk '{print $4}' 
  grep "ISCISHESS" "$file" | awk '{split($4, a, "_"); print a[4] "_" a[5]}'
}

Final_State() {
  local list=("$1")
  local file=${list%.*}.out
  # echo $file
  # 1. Check that the job is finished if not finished, return 0
  local finish=0
  local finish=$(grep "****ORCA ESD FINISHED WITHOUT ERROR****" $file | wc -l)
  # if [ $finish -eq 0 ]; then
  #   echo "99"
  #   return 
  # fi
  # grep "ISCISHESS" $file | awk '{print $4}' 
  grep "ISCFSHESS" "$file" | awk '{split($4, a, "_"); print a[4] "_" a[5]}'
}

molecules=('0CZ0' '0DA0' '0DB0' '0TD0' '1CZ3' '1CZ4' '1DA3' '1DB2' '1DB5' '1OB4' '1TD3' '1TD4' '1TD5')

for molecule in ${molecules[@]}; do
    # echo "molecule: $molecule"
    if [[ ! "$molecule" =~ ^[0-9] ]]; then
      continue
    fi
    cd $molecule
    echo "Molecule: $molecule"
    ref="0${molecule:1:2}0"
    echo "Reference: $ref"
    if [ "$ref" == "0OB0" ]; then
        ref="0DB0"
    fi

    for functional in "${functionals[@]}"; do
        GS="$molecule"_"$functional"_svp_s0_scf_optfreq
        ES=${molecule}_${functional}_svp_s1_Dscf_optfreq
        ES_td=${molecule}_${functional}_svp_s1_tddft_optfreq
        ES_2=${molecule}_${functional}_svp_s2_tddft_optfreq
        TS="$molecule"_"$functional"_svp_t1_Dscf_optfreq
        Hab="$molecule"_"$functional"_svp_s1_Hab_scf
        lam="$molecule"_"$functional"_svp_t1_lam
        FLUO="$molecule"_"$functional"_svp_s1_esd_fluo
        ISC_1="$molecule"_"$functional"_svp_t1_esd_isc_T1
        ISC_2="$molecule"_"$functional"_svp_t1_esd_isc_T2
        ISC_3="$molecule"_"$functional"_svp_t1_esd_isc_T3
        RISC_1="$molecule"_"$functional"_svp_t1_esd_risc_T1
        RISC_2="$molecule"_"$functional"_svp_t1_esd_risc_T2
        RISC_3="$molecule"_"$functional"_svp_t1_esd_risc_T3
        files=($GS $ES $TS $FLUO $ISC_1 $ISC_2 $ISC_3 $RISC_1 $RISC_2 $RISC_3)
        # if [ ! -f "$TS.out" ]; then
        T1=$(Final_State $ISC_1)
        TS="$molecule"_"$functional"_svp_"$T1"_optfreq
        # fi
        if [ ! -f "$ISC_1.out" ]; then
           TS="$molecule"_"$functional"_svp_t1_scf_optfreq
        fi
        
        # for file in "${files[@]}"; do
        #     echo "file: $file"
        # done
        # echo $file
        # finish=$(ORCA-chkjob -q "$file")
        # if [ "$finish" -eq 0 ]; then
        #     echo "!!!!!!!!!!!!!!!!!!! Job $file not finished"
        #     continue
        # fi
        if [ ! -f "$GS.out" ]; then
            echo "$GS.out not found"
            continue
        fi
        # check imaginary modes
        for s in $GS $ES $TS; do
            if [ ! -f "$s.hess" ]; then
                echo $s
                hess=1
            else
                freq=`grep --text "vibrational_frequencies" -A 8 $s.hess | tail -n 1 | awk '{print $2}'`
                if [[ "$freq" == -* ]]; then
                    echo $s.hess
                    # echo "Frequency 6: $freq"
                    hess=1
                else
                    hess=0
                fi
            fi
        done
        # freq_S0=`grep "vibrational_frequencies" -A 8 $GS.hess | tail -n 1 | awk '{print $2}'`
        # freq_S1=`grep "vibrational_frequencies" -A 8 $ES.hess | tail -n 1 | awk '{print $2}'`
        # freq_T1=`grep "vibrational_frequencies" -A 8 $TS.hess | tail -n 1 | awk '{print $2}'`
        # f=0
        # for freq in $freq_S0 $freq_S1 $freq_T1; do
        #     if [[ "$freq" == -* ]]; then
        #         echo "***** Vibrational mode 6 is an imaginary mode for $molecule with $functional, at ${states[$f]}"
        #         echo "Frequency 6: $freq"
        #         hess=1
        #     else
        #         hess=0
        #     fi
        #     f=$((f+1))
        # done

        SPE_S0=$(ORCA-GrepSPE -q "$GS.out")
        SPE_S1=$(ORCA-GrepSPE -q "$ES.out")
        SPE_S1_td=$(ORCA-GrepSPE -q "$ES_td.out")
        SPE_S2=$(ORCA-GrepSPE -q "$ES_2.out")
        SPE_T1=$(ORCA-GrepSPE -q "$TS.out")

        E_Hab_O3=$(ORCA-GrepSPE -q "$Hab.out" )
        # E_ES=$(ORCA-GrepSPE -q "$ES.out" )
        E_lam_O3=$(ORCA-GrepSPE -q "$lam.out" )
        # E_TS=$(ORCA-GrepSPE -q "$TS.out" )
        if [ "$SPE_S1" != "0" ] && [ "$SPE_T1" != "0" ]; then
            Energy_Gap=$(echo "($SPE_S1 - $SPE_T1) * 27.2114079527" | bc -l 2>/dev/null)
        else
            Energy_Gap=0.0000000000
        fi
        
        Fluorescence_rate=$(ORCA-Grepk -q "$FLUO.out")
        
        ISC_rate_1=$(ORCA-Grepk -q "$ISC_1.out")
        ISC_rate_2=$(ORCA-Grepk -q "$ISC_2.out")
        ISC_rate_3=$(ORCA-Grepk -q "$ISC_3.out")


        RISC_rate_1=$(ORCA-Grepk -q "$RISC_1.out")
        RISC_rate_2=$(ORCA-Grepk -q "$RISC_2.out")
        RISC_rate_3=$(ORCA-Grepk -q "$RISC_3.out")

        ST=$(grep 'DELE' $ISC_1.out | awk '{print $4}')
        # echo "ISC rate 1: $ISC_rate_1"
        # echo "ISC rate 2: $ISC_rate_2"
        # echo "ISC rate 3: $ISC_rate_3"



        # Make sure 1 and 3 are equal if one of them is zero
        if [ -z $ISC_rate_3 ] && [ "$ISC_rate_1" != "0.00000000e+00" ]; then
            ISC_rate_3=$ISC_rate_1
            # echo "Replaced ISC rate 3 with ISC rate 1"
        elif [ -z $ISC_rate_1 ] && [ "$ISC_rate_3" != "0.00000000e+00" ]; then
            ISC_rate_1=$ISC_rate_3
        fi

        if [ -z $RISC_rate_3 ] && [ "$RISC_rate_1" != "0.00000000e+00" ]; then
            RISC_rate_3=$RISC_rate_1
            # echo "Replaced RISC rate 3 with RISC rate 1"
        elif [ -z $RISC_rate_1 ] && [ "$RISC_rate_3" != "0.00000000e+00" ]; then
            RISC_rate_1=$RISC_rate_3
        fi
        ISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$ISC_rate_1" "$ISC_rate_2" "$ISC_rate_3" | bc -l 2>/dev/null)
        RISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$RISC_rate_1" "$RISC_rate_2" "$RISC_rate_3" | bc -l 2>/dev/null)
        # echo "ISC 1: $ISC_rate_1"
        # echo "ISC 2: $ISC_rate_2"
        # echo "ISC 3: $ISC_rate_3"
        # echo "ISC sum: $ISC_sum"
        # echo "RISC 1: $RISC_rate_1"
        # echo "RISC 2: $RISC_rate_2"
        # echo "RISC 3: $RISC_rate_3"
        # echo "RISC sum: $RISC_sum"
        if [ "$ISC_sum" != "0.00000000e+00" ]; then
            if (( $(echo "$ISC_sum < 0" | bc -l) )); then
                # echo "Negative ISC rate for $molecule with $functional"
                ISC_average="NaN"
            else
                ISC_average=$(printf "%.10g / 3\n" "$ISC_sum" | bc -l 2>/dev/null)
                # echo "ISC average: $ISC_average"
            fi
        else
            ISC_average=0.0000000000
        fi

        if [ "$RISC_sum" != "0.00000000e+00" ]; then
            if (( $(echo "$RISC_sum < 0" | bc -l) )); then
                # echo "Negative RISC rate for $molecule with $functional"
                RISC_average="NaN"
            else
                RISC_average=$(printf "%.10g / 3\n" "$RISC_sum" | bc -l 2>/dev/null)
                # echo "RISC average: $RISC_average"
            fi
        else
            RISC_average=0.0000000000
        fi

        if [ -f "$FLUO.spectrum" ]; then
            emission=$(ORCA-GrepSpectrum "$FLUO.spectrum")
            emission_wave=$(echo "$emission" | awk '{printf "%.2f\n", 1e7/$1}')
        else
            echo "$FLUO.spectrum not found"
            emission_wave=0.00
        fi
        # multiwfn_ana $FLUO s1
        # echo "RUNNING: multiwfn_ana $FLUO s1"

        # if [ -f "$FLUO.gbw" ]; then
        #     # echo "Multiwfn analysis for $FLUO"
        #     DIndex_S1=$(multiwfn_ana $FLUO)
        # else
        #     # echo "Multiwfn analysis for $FLUO.gbw"
        #     DIndex_S1=0
        # fi
       
        if [[ "${@}" =~ "offct" ]]; then
            DIndex_S1=$(~/bin/ORCA/multiwfn_ana $FLUO s1)
        else 
            DIndex_S1=$(grep "D index" $FLUO.out | tail -n 1 | awk '{print $9}')
        fi

        if [ ! -f "$TS.xyz" ]; then
            echo "$TS.xyz not found"
            continue
        fi
        if [ ! -f "$GS.xyz" ]; then
            echo "$GS.xyz not found"
            continue
        fi

        # XYZ_S1_S0=$(calculate_rmsd $ES.xyz $GS.xyz 2>&1)
        # XYZ_T1_S0=$(calculate_rmsd $TS.xyz $GS.xyz 2>&1)
        # XYZ_T1_S1=$(calculate_rmsd $TS.xyz $ES.xyz 2>&1)
        # if [ -f "$ES_td.xyz" ]; then
        #     XYZ_S1_S0_td=$(calculate_rmsd $ES_td.xyz $GS.xyz 2>&1)
        #     XYZ_T1_S1_td=$(calculate_rmsd $TS.xyz $ES_td.xyz 2>&1)
        # else
        #     XYZ_S1_S0_td=0
        #     XYZ_T1_S1_td=0
        # fi
        

        SPE_S0=$(printf "%.10f" "$SPE_S0")
        SPE_S1=$(printf "%.10f" "$SPE_S1")
        SPE_S1_td=$(printf "%.10f" "$SPE_S1_td")
        SPE_S2=$(printf "%.10f" "$SPE_S2")
        SPE_T1=$(printf "%.10f" "$SPE_T1")
        Energy_Gap=$(printf "%.10f" "$Energy_Gap")
        Fluorescence_rate=$(printf "%.8e" "$Fluorescence_rate")
        ISC_rate_1=$(printf "%.8e" "$ISC_rate_1")
        ISC_rate_2=$(printf "%.8e" "$ISC_rate_2")
        ISC_rate_3=$(printf "%.8e" "$ISC_rate_3")
        ISC_average=$(printf "%.8e" "$ISC_average")
        RISC_rate_1=$(printf "%.8e" "$RISC_rate_1")
        RISC_rate_2=$(printf "%.8e" "$RISC_rate_2")
        RISC_rate_3=$(printf "%.8e" "$RISC_rate_3")
        RISC_average=$(printf "%.8e" "$RISC_average")
        XYZ_S1_S0=$(printf "%.10f" "$XYZ_S1_S0")
        XYZ_T1_S1=$(printf "%.10f" "$XYZ_T1_S1")
        XYZ_T1_S0=$(printf "%.10f" "$XYZ_T1_S0")


        Gibbs_TS=$(grep "Final Gibbs free energy " "$TS.out" | awk '{print $6}')
        Gibbs_ES=$(grep "Final Gibbs free energy " "$ES.out" | awk '{print $6}')
        delta_G=$(echo "$Gibbs_TS - $Gibbs_ES" | bc -l 2> /dev/null)

        
        MarcusRate=$(MarcusCTRate -from $SPE_T1 -to $SPE_S1 -vHab $E_Hab_O3 -vlam $E_lam_O3 -dG $delta_G | awk '{print $5}' 2> /dev/null)
        if [ -z "$MarcusRate" ]; then
            MarcusRate="NaN"
        elif [ "$MarcusRate" == "0.00e+00" ]; then
            MarcusRate=""            
            # MarcusRate=$(printf "%.8e" "$MarcusRate")
        fi

        # $DIndex_S1=$(printf "%.3e" "$$DIndex_S1")
        # CT_T1=$(printf "%.3e" "$CT_T1")

        # echo "SPE_S0: $SPE_S0"
        # echo "SPE_S1: $SPE_S1"
        # echo "SPE_T1: $SPE_T1"
        # echo "Fluorescence rate for $molecule with $functional: $Fluorescence_rate"
        # echo "Energy Gap (S1 - T1) for $molecule with $functional: $Energy_Gap eV"
        # echo "ISC rate for $molecule with $functional: $ISC_average"
        # echo "RISC rate for $molecule with $functional: $RISC_average"
        # echo "Energy Gap (S1 - T1) for $molecule with $functional: $Energy_Gap eV"
        # Append the new data to the arrays



        if [ "$SPE_S0" == "0" ]; then
            if ! qjlist | grep -q "$GS"; then
                echo "$GS"  
            fi
        fi

        if [ "$SPE_S1"  == "0" ]; then
            if ! qjlist | grep -q "$ES"; then
                echo "$ES"
            fi
        fi

        if [ "$SPE_T1"  == "0" ]; then
            if ! qjlist | grep -q "$TS"; then
            echo "$TS"
            fi
        fi

        if [ "$Fluorescence_rate" == "0.00000000e+00" ]; then
            if ! qjlist | grep -q "$FLUO"; then
                echo "$FLUO"
            fi
        fi

        if [ "$ISC_rate_1" == "0.00000000e+00" ]; then
            echo "$ISC_1"
        fi
        if [ "$ISC_rate_2" == "0.00000000e+00" ]; then
            echo "$ISC_2"
        fi
        if [ "$ISC_rate_3" == "0.00000000e+00" ]; then
            echo "$ISC_3"
        fi

        if [ "$RISC_rate_1" == "0.00000000e+00" ]; then
            echo "$RISC_1"
        fi

        if [ "$RISC_rate_2" == "0.00000000e+00" ]; then
            echo "$RISC_2"
        fi

        if [ "$RISC_rate_3" == "0.00000000e+00" ]; then
            echo "$RISC_3"
        fi

        # echo "writing to $output"

        # Debugging: Print the values of the variables
        # echo "Debug: molecule=$molecule, functional=$functional, SPE_S0=$SPE_S0, SPE_S1=$SPE_S1, SPE_T1=$SPE_T1, Energy_Gap=$Energy_Gap, Fluorescence_rate=$Fluorescence_rate, ISC_rate_1=$ISC_rate_1, ISC_rate_2=$ISC_rate_2, ISC_rate_3=$ISC_rate_3, ISC_average=$ISC_average, RISC_rate_1=$RISC_rate_1, RISC_rate_2=$RISC_rate_2, RISC_rate_3=$RISC_rate_3, RISC_average=$RISC_average, DIndex_S1=$DIndex_S1, XYZ_S1_S0=$XYZ_S1_S0, XYZ_T1_S0=$XYZ_T1_S0, XYZ_T1_S1=$XYZ_T1_S1, ref=$ref"

        echo "${molecule},${functional},\"${SPE_S0}\",\"${SPE_S1}\",\"${SPE_S1_td}\",\"${SPE_T1}\",\"${Energy_Gap}\",\"${ST}\",\"${Fluorescence_rate}\",\"${ISC_rate_1}\",\"${ISC_rate_2}\",\"${ISC_rate_3}\",\"${ISC_average}\",\"${RISC_rate_1}\",\"${RISC_rate_2}\",\"${RISC_rate_3}\",\"${RISC_average}\",\"${MarcusRate}\",\"${emission_wave}\",\"${ref}\"" >> ../$output
        


    done
    cd ..
done

# {
#     for ((i=0; i<${#MoleculeNames[@]}; i++)); do
#         echo "${MoleculeNames[i]},${Functionals[i]},${spe_s0[i]},${spe_s1[i]},${spe_t1[i]},${energy_gap[i]},${fluorescence_rate[i]},${isc_rate_1[i]},${isc_rate_2[i]},${isc_rate_3[i]},${isc_rate_avg[i]},${risc_rate_1[i]},${risc_rate_2[i]},${risc_rate_3[i]},${risc_rate_avg[i]},${CT_S1[i]},${xyz_S1_S0[i]},${xyz_T1_S0[i]},${xyz_T1_S1[i]},${REF[i]}"
#     done
# } >> $output

# echo "Data has been processed and saved to $output"