#!/bin/bash
set -e  # Exit immediately if a command exits with a non-zero status
input=${1%.*}
$PROJECT/orca_6_0_0/orca_2mkl $input -molden > /dev/null 2>&1
output=multiwfn_${input}.out

# Create calcall.txt with initial content
echo "18" > calcall.txt  # 18 Electron excitation analysis
echo "1" >> calcall.txt  # 1 Calculate hole
echo "$input.out" >> calcall.txt  # Output file
echo "1" >> calcall.txt  # Singlet
echo "1" >> calcall.txt  # S1
echo "" >> calcall.txt  # Empty line
echo "1" >> calcall.txt  # 1 Analyze hole in S1
echo "2" >> calcall.txt  # 1 medium gird
echo "0" >> calcall.txt  # 0 return to post process
echo "0" >> calcall.txt  # 0 return to hole-electron
echo "0" >> calcall.txt  # 0 return to main menu
echo "q" >> calcall.txt  # q quit

# Run Multiwfn command and capture output
Multiwfn $input.molden.input < calcall.txt > out.txt
# echo "finished"
# Remove temporary files (commented out for debugging)
# rm -f ./calcall.txt ./result.txt
# Search for specific patterns in out.txt and append results to result.txt
grep "Sr index" ./out.txt >> result.txt
grep "D index" ./out.txt  >> result.txt
grep "RMSD of electron in" ./out.txt >> result.txt
grep "H index" ./out.txt >> result.txt
grep "t index" ./out.txt >> result.txt
echo
echo "Multiwfn Finished!"

D_Index=$(grep "D index" ./out.txt | awk '{print $9}')
echo "D index: $D_Index"