#!/bin/bash

for file in "$@"; do
    name=${file%.*}
    if [ ! -f ~/scratch/orcacalc/$name/$name.out ]; then
        continue
    fi
    echo "------------------------ --------------------------------- ------------------------------------"
    grep "GEOMETRY OPTIMIZATION CYCLE" ~/scratch/orcacalc/$name/$name.out | tail -n 1
    echo "~/scratch/orcacalc/$name/$name.out ::"
    echo " "
    tail -n 6 ~/scratch/orcacalc/$name/$name.out

    echo "----------------------------------------------------------------------------------------------"
    # echo " "
done 