#!/bin/bash


for file in "$@"; do
  input=${file%.*}
  file_K=${input}_Kvector.data
  file_HR=${input}_HRfactor.data
  file_lamda=${input}_lamda.data

  if [ ! -f $input.out ]; then
      echo "Error: $input.out not found"
      continue
  fi

  if ! grep -q "will need at least" $input.out; then
      echo "Error: 'number of modes' not found in $input.out"
      continue
  fi

  if ! grep -q "The Huang-Rhys factor per mode is:" $input.out; then
      echo "Error: 'The Huang-Rhys factor per mode is:' not found in $input.out"
      continue
  fi

  if ! grep -q "The K vector (a.u.) is:" $input.out; then
      echo "Error: 'The K vector (a.u.) is:' not found in $input.out"
      continue
  fi

  if ! grep -q "The reorganization energy per mode is:" $input.out; then
      echo "Error: 'The reorganization energy per mode is:' not found in $input.out"
      continue
  fi

  nmode=$(grep "will need at least" $input.out | awk '{print $5}')
  grep -A $((nmode + 5)) "The Huang-Rhys factor per mode is:" $input.out | tail -n +6  > $file_HR
  grep -A $((nmode + 5)) "The K vector (a.u.) is:" $input.out | tail -n +6  > $file_K
  grep -A $((nmode + 5)) "The reorganization energy per mode is:" $input.out | tail -n +6  > $file_lamda
  paste $file_lamda <(awk '{print $3}' $file_HR) > temp && mv -f temp $file_lamda 
done
