#!/bin/bash



if [ "$1" == "-q" ]; then
    shift
    for file in "$@"; do
        finish=$(grep -c "****ORCA TERMINATED NORMALLY****" ${file%.*}.out)
        echo "$finish"
    done
else
    for file in "$@"; do
        if [ ! -f ${file%.*}.out ]; then
            echo "$file ORCA output file does not exist."
            continue
        fi
        finish=$(grep -c "****ORCA TERMINATED NORMALLY****" ${file%.*}.out)
        if [ $finish -eq 1 ]; then
            continue
        else
            echo "$file ORCA did not terminate normally."
        fi
    done
fi

exit 0