#!/bin/bash

if [ "$1" == "-q" ]; then
  init=${2%.*}.out
  final=${3%.*}.out
  Energy1=`grep --text "Electronic Energy " $init | tail -n 1 | awk '{print $4}'`

  Energy2=`grep --text "Electronic Energy " $final | tail -n 1 | awk '{print $4}'`

  DiffEnergy=$(echo "($Energy2 - $Energy1) * 219474.6" | bc)

  echo "$DiffEnergy"
else
  init=${1%.*}.out
  final=${2%.*}.out
  Energy1=`grep --text "Electronic Energy " $init | tail -n 1 | awk '{print $4}'`

  Energy2=`grep --text "Electronic Energy " $final | awk '{print $4}'`

  echo $Energy1

  echo $Energy2

  DiffEnergy=$(echo "($Energy2 - $Energy1) * 219474.6" | bc)

  echo "$DiffEnergy"
fi