#!/bin/bash


orca_pltvib=/home/project/11003762/orca_6_0_0/orca_pltvib

hess=${1%.*}.hess
oldcoord=${1%.*}.xyz

# Check if the hessian file exists
if [ ! -f $hess ]; then
  echo "$hess not found. Exiting..."
  exit 1
else 
  echo "$hess found."
fi

# Check if there is any imaginary mode
freq=`grep --text "vibrational_frequencies" -A 8 $hess | tail -n 1 | awk '{print $2}'`

if [[ "$freq" == -* ]]; then
  echo "Vibrational mode 6 is an imaginary mode."
  echo "Frequency 6: $freq"
else
  echo "Frequency 6: $freq"
  echo "No imaginary mode found. Exiting..."
  exit 1
fi

# Genreate mode xyz
echo "Generating mode xyz file for vibrational mode 6..."
$orca_pltvib $hess 6

mode=${1%.*}.hess.v006.xyz

# Check if the mode xyz file exists
if [ ! -f $mode ]; then
  echo "$mode not found. Exiting..."
  exit 1
fi

# Generate the displacement
# Step 1: Extract the lines and remove the last one
echo "Generating the displacement for vibrational mode 6..."
awk '/\* Frequency\(6\)/{count++} count >= 6 && count < 7' $mode | head -n -1 > temp_extracted.txt


awk '{if (NF > 4) print $1, $2, $3, $4; else print $0}' temp_extracted.txt > temp_extracted_filtered.txt

mv temp_extracted_filtered.txt temp_extracted.txt

# Step 2: Replace from the second line in benzene.xyz and save it as a new file
{ head -n 1 $oldcoord; cat temp_extracted.txt; } > ${1%.*}_v006.xyz

echo "Displacement file ${1%.*}_v006.xyz created."

rm $mode
rm temp_extracted.txt


