#!/bin/bash

# grep "FINAL SINGLE" $1 | tail -n 1 

# If there are multiple files

if [ "$1" == "-q" ]; then
    for file in "${@:2}"; do
        if [ ! -f "$file" ]; then
            # echo "File $file does not exist."
            continue
        fi
        constant=$(grep --text "rate constant" $file | awk '{ print $7 }')
        if [ -z "$constant" ]; then
            constant=0
        fi
        echo "$constant"
    done
else
    for file in "$@"; do
        # echo "File: $file"
        if [ ! -f "$file" ]; then
            echo "File $file does not exist."
            continue
        fi
        file=${file%.*}
        constant=$(grep --text "rate constant" ${file}.out | awk '{ print $7 }')
        if [ -z "$constant" ]; then
            constant=0
        fi
        echo -e "$file: \t $constant"
        # echo ""
    done
fi

exit 0

