#!/bin/bash
if [[ $(hostname) == *"atlas"* ]]; then
    source /etc/profile.d/modules.sh
fi
# Check for input file
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 [-q] <molden_file>"
    exit 1
fi

quiet_mode=false

# Check for -q option
if [[ "$1" == "-q" ]]; then
    quiet_mode=true
    shift
fi

for filename in "$@"; do
    file=${filename%.*}
    op=$file.orb
    version=$(grep " Program Version" $file.out | awk '{print $3}')
    if [[ $(hostname) == *"atlas"* ]]; then
        if [ "$version" == "6.1.0" ]; then
            $ORCA_ROOT/orca_2mkl ${file}.gbw -molden > /dev/null 2>&1
        elif [ "$version" == "6.0.1" ]; then
            orca_2mkl $file.gbw -molden > /dev/null 2>&1
        elif [ "$version" == "6.0.0" ]; then
            module purge ORCA/6.0.1-foss-2023b
            module load ORCA/6.0.0-foss-2023b_xtb_6.7.1
            orca_2mkl $file.gbw -molden > /dev/null 2>&1
            module purge ORCA/6.0.0-foss-2023b_xtb_6.7.1
            module load ORCA/6.0.1-foss-2023b
        else
            echo "Unknown ORCA version for $file: $version" 
            continue
        fi
    fi
    # $ORCA_ROOT/orca_2mkl $file -molden  > /dev/null 2>&1
    norb=$(grep "Alpha" $file.molden.input | wc -l)
    HOMO=$(ORCA-GrepHOMO -q $file)
    LUMO=$(($HOMO + 1))
    # echo "HOMO: $HOMO"
    from=$(($HOMO - 10))
    to=$(($HOMO + 12))
    occ=$(grep "ORBITAL ENERGIES" $file.out -A 5 | tail -n 1 | awk '{print $2}')

    if [ "$(echo "$occ == 1.0" | bc)" -eq 1 ]; then
        # echo "1"
        search="SPIN UP ORBITALS"
    else
        # echo "Not 1"
        search="ORBITAL ENERGIES"
    fi

    # grep "$search" $file.out -A $to | tail -n 20 | sort -k3 -n | grep $LUMO -B 3 -A 3
    # grep "$search"  $file.out -A $to | tail -n 20  | sort -k3 -n | grep $LUMO -B 1
    orbital=$(grep "$search"  $file.out -A $to | tail -n 20  | sort -k3 -n | grep " $LUMO "  -B 1 | head -n 1 | awk '{print $1}')
    excited_orbital=$(($orbital + 1))
    
    if $quiet_mode; then
        # echo "$excited_orbital"
        echo "$excited_orbital -> $LUMO"
    else
        grep "$search" $file.out -A $to | tail -n 20 | sort -k3 -n | grep $LUMO -B 3 -A 3
        echo "$excited_orbital -> $LUMO"
    fi
done
