#!/bin/bash


if [[ $(whoami) == *"e0732532"* ]]; then
  Host="hpc"
  scratch=/hpctmp/e0732532
  # ORCA_ROOT=/app1/ebapps/arches/flat/software/ORCA/6.0.1-foss-2023b/bin/
  THEO_ROOT=/home/svu/e0732532/software/TheoDORE_3.2
  template=/home/svu/e0732532/bin/dens_ana_template
#   echo "atlas"
#   echo $scratch
elif [[ $(whoami) == *"e0732533"* ]]; then
  Host="nscc"
  scratch=/home/users/nus/$USER/orca_6_0_0
  # ORCA_ROOT=/home/project/11004127/Elusy/software/orca_6_0_0
  ORCA_ROOT=/home/project/11004127/software/orca601_avx2
  THEO_ROOT=/home/users/nus/e0732533/Software/TheoDORE_3.2
  template=/home/users/nus/e0732533/bin/dens_ana_template
#   echo "nscc"
elif [[ $(hostname) == *"Precision"* ]]; then
  Host="bohr"
  scratch=/home/scratch/hanqi/orca
#   echo "bohr"
fi

orca_pltvib=$ORCA_ROOT/orca_pltvib

hess=${1%.*}.hess
oldcoord=${1%.*}.xyz

# Check if the hessian file exists
if [ ! -f $hess ]; then
  echo "$hess not found. Exiting..."
  exit 1
else 
  echo "$hess found."
fi

# Check if there is any imaginary mode
freq=`grep --text "vibrational_frequencies" -A 8 $hess | tail -n 1 | awk '{print $2}'`

if [[ "$freq" == -* ]]; then
  echo "Vibrational mode 6 is an imaginary mode."
  echo "Frequency 6: $freq"
else
  echo "Frequency 6: $freq"
  echo "No imaginary mode found. Exiting..."
  exit 1
fi

# Genreate mode xyz
echo "Generating mode xyz file for vibrational mode 6..."
$orca_pltvib $hess 6

mode=${1%.*}.hess.v006.xyz

# Check if the mode xyz file exists
if [ ! -f $mode ]; then
  echo "$mode not found. Exiting..."
  exit 1
fi

# Generate the displacement
# Step 1: Extract the lines and remove the last one
echo "Generating the displacement for vibrational mode 6..."
awk '/\* Frequency\(6\)/{count++} count >= 17 && count < 18' $mode | head -n -1 > temp_extracted.txt


awk '{if (NF > 4) print $1, $2, $3, $4; else print $0}' temp_extracted.txt > temp_extracted_filtered.txt

mv temp_extracted_filtered.txt temp_extracted.txt

# Step 2: Replace from the second line in benzene.xyz and save it as a new file
{ head -n 1 $oldcoord; cat temp_extracted.txt; } > ${1%.*}_v006.xyz

echo "Displacement file ${1%.*}_v006.xyz created."

rm $mode
rm temp_extracted.txt


