#!/bin/bash

state=1
quiet=0
initial=0
final=0

process_file() {
  local file=$1
  local state=$2
  local f=${file%.*}
  local tstat=$((state+1))

  if grep -q "STATE 1" "$file"; then
    local list=$(grep -A 15 "STATE *$state:" "$f.out" | tail -n 28 | grep -B 18 "STATE *$tstat:" | head -n -2 | sort -k5,5n | tail -n 1)
     from=$(echo "$list" | awk '{print $1}' | cut -d'a' -f1)
     to=$(echo "$list" | awk '{print $3}' | cut -d'a' -f1)
     nexcit=$((to-from))
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -q)
      quiet=1
      shift
      ;;
    -s)
      state=$2
      shift 2
      ;;
    -i)
      initial=1
      shift
      ;;
    -f)
      final=1
      shift
      ;;
    *)
      break
      ;;
  esac
done

for file in "$@"; do
  process_file "$file" "$state"
  if [ "$quiet" -eq 1 ]; then
    echo "$nexcit"
    continue
  elif [ "$initial" -eq 1 ]; then
    echo "$from"
  elif [ "$final" -eq 1 ]; then
    echo "$to"
  else
    echo -e "$f STATE $state: \t $from to $to \t $nexcit"
  fi

done