#!/bin/bash

# Check for input file
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 [-q] <molden_file>"
    exit 1
fi

quiet_mode=false

# Check for -q option
if [[ "$1" == "-q" ]]; then
    quiet_mode=true
    shift
fi

for filename in "$@"; do
    file=${filename%.*}
    op=$file.orb
    $ORCA_ROOT/orca_2mkl $file -molden  #> /dev/null 2>&1
    norb=$(grep "Alpha" $file.molden.input | wc -l)
    HOMO=$(ORCA-GrepHOMO -q $file)
    LUMO=$(($HOMO + 1))
    # echo "HOMO: $HOMO"
    from=$(($HOMO - 10))
    to=$(($HOMO + 12))
    occ=$(grep "ORBITAL ENERGIES" $file.out -A 5 | tail -n 1 | awk '{print $2}')

    if [ "$(echo "$occ == 1.0" | bc)" -eq 1 ]; then
        # echo "1"
        search="SPIN UP ORBITALS"
    else
        # echo "Not 1"
        search="ORBITAL ENERGIES"
    fi

    # grep "$search" $file.out -A $to | tail -n 20 | sort -k3 -n | grep $LUMO -B 3 -A 3
    # grep "$search"  $file.out -A $to | tail -n 20  | sort -k3 -n | grep $LUMO -B 1
    orbital=$(grep "$search"  $file.out -A $to | tail -n 20  | sort -k3 -n | grep " $LUMO "  -B 1 | head -n 1 | awk '{print $1}')
    excited_orbital=$(($orbital + 1))
    
    if $quiet_mode; then
        # echo "$excited_orbital"
        echo "$excited_orbital -> $LUMO"
    else
        grep "$search" $file.out -A $to | tail -n 20 | sort -k3 -n | grep $LUMO -B 3 -A 3
        echo "$excited_orbital -> $LUMO"
    fi
done
