#!/bin/bash

if [[ $(hostname) == *"atlas"* ]]; then
  Host="hpc"
  scratch=/hpctmp/$USER
elif [[ $(hostname) == *"asp2a"* ]]; then
  Host="nscc"
  scratch=/home/users/nus/$USER/scratch/orcacalc/
elif [[ $(hostname) == *"Precision"* ]]; then
  Host="bohr"
  scratch=/home/scratch/hanqi/orca/
elif [[ $(hostname) == *"colo-chmlu"* ]]; then
  Host="chmlu"
  scratch=/scratch/Elusy/orcacalc/
else
  echo "Unknown host. Please set the scratch directory manually."
  exit 1
fi

for file in "$@"; do
    name=${file%.*}
        if [ ! -f $scratch/$name/$name.out ]; then
        continue
        fi
        echo "------------------------ --------------------------------- ------------------------------------"
        grep "GEOMETRY OPTIMIZATION CYCLE" $scratch/$name/$name.out | tail -n 1
        echo "----------------------------------------------------------------------------------------------"
        echo "$scratch/$name/$name.out"
        echo " "
        tail $scratch/$name/$name.out
        echo " "

done 