#!/bin/bash

state=1

process_file() {
  local file=$1
  local state=$2
  local f=${file%.*}
  local tstat=$((state+1))

  if grep -q "STATE 1" "$file"; then
    local list=$(grep -A 10 "STATE  $state:" "$file" | tail -n 10 | grep -B 5 "STATE  $tstat:" | head -n -2 | sort -k5,5n | tail -n 1)
    local from=$(echo "$list" | awk '{print $1}' | cut -d'a' -f1)
    local to=$(echo "$list" | awk '{print $3}' | cut -d'a' -f1)
    local nexcit=$((to-from))
    echo -e "$f:\t$from to $to \t $nexcit"
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -q)
      shift
      for file in "$@"; do
        process_file "$file" 1
      done
      break
      ;;
    -s)
      state=$2
      shift 2
      for file in "$@"; do
        process_file "$file" "$state"
      done
      break
      ;;
    *)
      for file in "$@"; do
        process_file "$file" "$state"
      done
      break
      ;;
  esac
done
