#!/bin/bash

for filename in "$@"; do
    file=${filename%.*}
    op=$file.orb
    # $ORCA_ROOT/orca_2mkl $file -molden
    norb=$(grep "Alpha" $file.molden.input | wc -l)
    HOMO=$(ORCA-GrepHOMO -q $file)
    LUMO=$(($HOMO + 1))
    # echo $HOMO
    from=$(($HOMO - 10))
    to=$(($HOMO + 5))
    # for ((i=0; i<norb; i++)); do
    #     Ene=$(grep "Ene=" $file.molden.input | sed -n "$((i+1))p" | awk '{print $2}')
    #     Occup=$(grep "Occup" $file.molden.input | sed -n "$((i+1))p" | awk '{print $2}')
    #     # echo -e "$i\t $Ene" > $op
    # done
    # output=""
    # for ((i=$from; i<$to; i++)); do
    #     Ene=$(grep "Ene=" $file.molden.input | sed -n "$((i+1))p" | awk '{print $2}')
    #     Occup=$(grep "Occup" $file.molden.input | sed -n "$((i+1))p" | awk '{print $2}')
    #     output+="$i\t $Ene\t $Occup\n"
    # done
    # echo -e "$output" | sort -k2 -n
    # echo $HOMO
    grep "SPIN UP ORBITALS" $file.out -A $to | tail -n 8  | sort -k3 -n | grep $LUMO -B 3 -A 3
    excited_orbital=$(grep "SPIN UP ORBITALS" $file.out -A $to | tail -n 8  | sort -k3 -n | grep $LUMO -B 1 | head -n 1 | awk '{print $1}')
    echo "$excited_orbital -> $LUMO"
    
    
done 
# Check for input file
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <molden_file>"
    exit 1
fi

# # Call the function and display the total orbitals
# molden_file="$1"
# total_orbitals=$(calculate_orbitals "$molden_file")
# echo "Total orbitals: $total_orbitals"
