#!/bin/bash

# grep "FINAL SINGLE" $1 | tail -n 1 

# If there are multiple files

if [ "$1" == "-q" ]; then
    for file in "${@:2}"; do
        f=${file%.*}
        if [ ! -f "$f.out" ]; then
            # echo "File $file does not exist."
            continue
        fi
        SPE=$(grep --text "FINAL SINGLE POINT ENERGY" "$f.out" | tail -n 1 | awk '{print $5}')
        if [ -z "$SPE" ]; then
            SPE=0
        fi
        echo "$SPE"
    done
else
    for file in "$@"; do
        f=${file%.*}
        if [ ! -f "$f.out" ]; then
            echo "File $f.out does not exist."
            continue
        fi
        SPE=$(grep --text "FINAL SINGLE POINT ENERGY" "$f.out" | tail -n 1 | awk '{print $5}')
        if [ -z "$SPE" ]; then
            SPE=0
        fi
        echo -e "$f.out: \t $SPE"
        # echo ""
    done
fi

exit 0