#!/bin/bash

#PBS -q colo-chmlu 
#PBS -l select=1:ncpus=CR:host=colo-chmlu-08:mpiprocs=CR:mem=120GB
#PBS -j oe
#PBS -m abe
#PBS -p 1023

input=RN
orbital=WF          # input file for restart the calculation, if needed

#---------------------------------------------------------------------------
#   normally you should not need to change anything below this line
source /app1/ebenv
# module load ORCA/6.0.1-foss-2023b-avx2
EBENV_AVX2=1 
#---------------------------------------------------------------------------
#   normally you should not need to change anything below this line
# export ORCA_ROOT=/app1/ebapps/arches/flat-avx2/software/ORCA/6.0.1-foss-2023b-avx2/bin/
export ORCA_ROOT=/hpctmp/e0732532/orca_6_1_0
export PATH=$ORCA_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$ORCA_ROOT/lib:$LD_LIBRARY_PATH
export PATH=$HOME/bin/ORCA:$PATH
export MPI_ROOT=/app1/ebapps/arches/flat/software/OpenMPI/4.1.6-GCC-13.2.0
export PATH=$MPI_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$MPI_ROOT/lib:$LD_LIBRARY_PATH


CurrDir=$PBS_O_WORKDIR
cd $CurrDir

export OMP_NUM_THREADS=1

# scratch folder. Make it "input- dependent"
tdir=/hpctmp/e0732532/${input%.inp}

if [ ! -d $tdir ] ; then
    mkdir -p $tdir
else
    rm -rf  $tdir/*
fi

cd $tdir
echo "ORCA calculation is being executed in: "$tdir
echo `pwd`

cp -v $CurrDir/$input      $tdir/$input

if grep -q "* XYZFILE" $CurrDir/$input; then
  XYZFILE=`grep "* XYZFILE" $CurrDir/$input | awk '{print $5}'` 
  cp -v $CurrDir/$XYZFILE $tdir/
else
  XYZFILE=${input%.inp}.xyz
fi

echo "XYZ file: $XYZFILE"
# if it is a restart calcualtion, then check if the $orbital is
# exactly the same as ${input%.inp}.gbw. They must differ
if [ -f $CurrDir/$orbital ]; then
   if [ "$orbital" -eq "${input%.inp}.gbw" ] ; then
      echo "Restart GBW file is identical to ${input%.inp}.gbw. "
      echo "Please give a different name."
      echo "GBW file given for restart: " $orbital
      echo "GBW of this calculation   : " ${input%.inp}.gbw
   else
      # correct case: copy the file to $tdir
      cp $CurrDir/$orbital    $tdir/$orbital
   fi
fi


$ORCA_ROOT/orca $input > ${input%.inp}.out 2> ${input%.inp}.err &
ORCA_PID=$!  # $! stores the PID of the last background command

echo "ORCA calculation started with PID: $ORCA_PID"
echo "Checking the calculation status..."
echo -e "\t Cycle \t IROOT \t Mult \t Ediffs"
i=0
c=0
while [ $i -lt 1 ] ; do
  if ! kill -0 $ORCA_PID 2>/dev/null; then
      # If process is dead, check if it finished normally
      if grep -q "ORCA TERMINATED NORMALLY" ${input%.inp}.out; then
            echo "Calculation finished successfully."
            i=1
            break
      else
            echo "ORCA process died unexpectedly (crash/error)!"
            exit 1
      fi
  fi

    sleep 500
    finished=$(grep "ORCA TERMINATED NORMALLY" ${input%.inp}.out | wc -l)
    iroot=$(grep "The IROOT now is:" ${input%.inp}.out | tail -n 1 | awk '{print $6}')
    mult=$(grep "STATE  $iroot" ${input%.inp}.out | tail -n 1 | awk '{print $14}')
    opt=$(grep "GEOMETRY OPTIMIZATION CYCLE" ${input%.inp}.out | tail -n 1 | awk '{print $5}')
    Ediffs=$(grep "E diff. (CI)" ${input%.inp}.out | tail -n 1 | awk '{print $4}')
    if [ -z "$iroot" ]; then
      iroot=0
      continue
    fi

    if [ $mult -eq 1 ] ; then
      echo -e "\t $opt \t $iroot \t $mult \t $Ediffs"
       continue
    fi

    if [ $mult -gt 1 ] ; then
      echo -e "\t $opt \t $iroot \t $mult \t $Ediffs"
      echo "IROOT identification failed, restarting the program..."
      # kill the previous process
      kill $ORCA_PID
      wait $ORCA_PID 2>/dev/null # Wait for it to actually close

      sleep 120

      # restart the calculation with the new geometry 
      cp -v ${input%.inp}.xyz  restart.xyz.i$c
      cp -v ${input%.inp}.out  restart.out.i$c
    #   cp -v ${input%.inp}.gbw  restart.gbw.i$0
      # identify the new iroot 
      new_iroot=$(grep "Mult 1" ${input%.inp}.out | tail -n 1 | awk '{print $2}')
      new_iroot=${new_iroot:0:1}
      sed -i "/IROOT/c\IROOT $new_iroot" $input
      sed -i "s/$XYZFILE/${input%.inp}.xyz/g" $input

      $ORCA_ROOT/orca $input > ${input%.inp}.out 2> ${input%.inp}.err & 
      ORCA_PID=$!
      echo "Restarted ORCA with new PID: $ORCA_PID"
      c=$((c+1))
      continue
    fi 
    if [ $finished -gt 0 ] ; then
       i=1
    fi
done

wait $ORCA_PID


  if [ -f $tdir/${input%.inp}.property.txt ]; then
    $ORCA_ROOT/orca_2json $tdir/${input%.inp} -property
  fi



#   if the calculation is successful, then copy the
#   useful files back the original folder
#if [ $? -eq 0 ]; then
   if [ -f  $tdir/${input%.inp}.out           ] ; then  cp $tdir/${input%.inp}.out           $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.err           ] ; then  cp $tdir/${input%.inp}.err           $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.densitiesinfo ] ; then  cp $tdir/${input%.inp}.densitiesinfo $CurrDir/  ; fi ;
   if [ -f  $tdir/*.cube                      ] ; then  cp $tdir/*.cube                      $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.trj           ] ; then  cp $tdir/${input%.inp}.trj           $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.cis           ] ; then  cp $tdir/${input%.inp}.cis           $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.xyz           ] ; then  cp $tdir/${input%.inp}.xyz           $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.property.json ] ; then  cp $tdir/${input%.inp}.property.json $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.plt           ] ; then  cp $tdir/${input%.inp}.plt           $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.hess          ] ; then  cp $tdir/${input%.inp}.hess          $CurrDir/  ; fi ;
  #  if [ -f  $tdir/${input%.inp}.property.txt  ] ; then  cp $tdir/${input%.inp}.property.txt  $CurrDir/  ; fi ;
#   if [ -f  $tdir/${input%.inp}_property.txt ] ; then  cp $tdir/${input%.inp}_property.txt  $CurrDir/  ; fi ;
   if [ -f  $tdir/${input%.inp}.gbw           ] ; then  cp $tdir/${input%.inp}.gbw           $CurrDir/  ; fi ;   
#   cp $tdir/*.plt $CurrDir/
#fi

#-----------------------------------------------------

exit $?

