#!/bin/bash

atom_list="$(dirname "$0")/atom_list"
functionals=("O3LYP" "pbe0" "camB3LYP" "M062X")
template="/home/svu/e0732532/software/TheoDORE_3.2/template"

echo "Molecule_Name,Functional,Theodore_EHD1,Theodore_EHD2,Theodore_EHD3,Gap1,Gap2,Gap3,Excitation_Orbital1,Excitation_Orbital2,Excitation_Orbital3 " > theo_ana.csv

# echo "Reading atom list from $atom_list"
if [[ $(hostname) == *"atlas"* ]]; then
  Host="hpc"
  scratch=/hpctmp/e0732532
  ORCA_ROOT=/app1/ebapps/arches/flat/software/ORCA/6.0.1-foss-2023b/bin/
  THEO_ROOT=/home/svu/e0732532/software/TheoDORE_3.2
  template=/home/svu/e0732532/bin/dens_ana_template
#   echo "atlas"
#   echo $scratch
elif [[ $(hostname) == *"asp2a"* ]]; then
  Host="nscc"
  scratch=/home/users/nus/$USER/orca_6_0_0
  # ORCA_ROOT=/home/project/11004127/Elusy/software/orca_6_0_0
  ORCA_ROOT=/home/project/11004127/software/orca601_avx2
  THEO_ROOT=/home/users/nus/e0732533/Software/TheoDORE_3.2
  template=/home/users/nus/e0732533/bin/dens_ana_template
#   echo "nscc"
elif [[ $(hostname) == *"Precision"* ]]; then
  Host="bohr"
  scratch=/home/scratch/hanqi/orca
#   echo "bohr"
fi

template="$(dirname "$0")/dens_ana_template"

molecule_list=()
accepter_list=()
donor1_list=()
donor2_list=()

while IFS=$'\t' read -r molecule Accepter Donor1 Donor2; do
  molecule_list+=("$molecule")
  accepter_list+=("$Accepter")
  donor1_list+=("$Donor1")
  donor2_list+=("$Donor2")
done < "$atom_list"

echo "Molecule list: ${molecule_list[@]}" # ; echo "Accepter list: ${accepter_list[@]}" ; echo "Donor1 list: ${donor1_list[@]}" ; echo "Donor2 list: ${donor2_list[@]}"

# molecule_list=("${molecule_list[0]}")
# accepter_list=("${accepter_list[0]}")
# donor1_list=("${donor1_list[0]}")
# donor2_list=("${donor2_list[0]}")

# echo "Molecule list: ${molecule_list[@]}"
i=0
for molecule in "${molecule_list[@]}"; do
  molecule=${molecule_list[$i]}
  accepter=${accepter_list[$i]}
  donor1=${donor1_list[$i]}
  echo "Molecule: $molecule"  ; echo "Accepter: $accepter"; echo "Donor1: $donor1"; echo "Donor2: $donor2"
  cd $molecule
  for f in 0 1 2; do
    func=${functionals[$f]}
    FLUO="$molecule"_"$func"_svp_s1_esd_fluo
    echo "Calculating e-h distance for $FLUO"
    $ORCA_ROOT/orca_2mkl $FLUO -molden  > /dev/null 2>&1
    sed -e "s/NAME/$FLUO/g" $template > den_ana_$FLUO.in
    sed -i "s/DONOR/$donor1/g" den_ana_$FLUO.in
    sed -i "s/ACCEPTOR/$accepter/g" den_ana_$FLUO.in
    exc_orb1=$(ORCA-GrepExcitation -q $FLUO.out)
    exc_orb2=$(ORCA-GrepExcitation -q -s 2 $FLUO.out)
    exc_orb3=$(ORCA-GrepExcitation -q -s 3 $FLUO.out)
    $ORCA_ROOT/orca_2mkl $input -molden > /dev/null 2>&1
    cp $FLUO.cis orca.cis
    theodore analyze_tden -f den_ana_$FLUO.in > summ_den_ana_$FLUO.txt
    EHD1=$(grep "1(1)A " theo_$FLUO.txt | awk '{print $10}')
    EHD2=$(grep "2(1)A " theo_$FLUO.txt | awk '{print $10}')
    EHD3=$(grep "3(1)A " theo_$FLUO.txt | awk '{print $10}')
    gap1=$(grep "1(1)A " theo_$FLUO.txt | awk '{print $2}')
    gap2=$(grep "2(1)A " theo_$FLUO.txt | awk '{print $2}')
    gap3=$(grep "3(1)A " theo_$FLUO.txt | awk '{print $2}')
    echo "e-h disctance for $func: $EHD1, $EHD2, $EHD3"
# echo "Molecule_Name,Functional,Theodore_EHD1,Theodore_EHD2,Theodore_EHD3,Gap1,Gap2,Gap3,Excitation_Orbital1, Excitation_Orbital2" > theo_ana.csv
    echo "$molecule,$func,$EHD1,$EHD2,$EHD3,$gap1,$gap2,$gap3,$exc_orb1,$exc_orb2" >> ../theo_ana.csv

  done
  cd ..
  i=$((i+1))
done

exit 0